proxmox:
  url:
    ip: "your-proxmox-host.example.com"   # Replace with your Proxmox host IP or FQDN
    port: 8006
  auth:
    username: "root@pam"                  # Replace with your Proxmox auth details
    password: "YOUR_SECURE_PASSWORD"      # Replace with a valid password or consider a special user

parameters:
  deviation: 4             # Percentage of allowable deviation for RAM load
  threshold: 90            # Threshold for cluster RAM load percentage
  lxc_migration: OFF       # Disable LXC migrations if not desired
  migration_timeout: 1000
  only_on_master: OFF       # Set to ON if you only want to run on the HA master
  test_mode: ON             # ON for test/simulation mode, OFF for live balancing

exclusions:
  vms: []     # Add VM IDs or ranges if you want to exclude certain VMs
  nodes: []   # Add node names to exclude certain nodes from balancing

groups:
  group1:
    - node1
    - node2
    - node3
    - node4
  group2:
    - node5
    - node6
    - node7

balancing:
  weight_ram: 0.5             # Relative importance of RAM balancing
  weight_cpu: 0.5             # Relative importance of CPU balancing
  memory_oom_threshold: 96    # OOM risk threshold for memory usage (%)
  cpu_threshold: 70           # CPU usage threshold (%) for triggering balancing

logging_level: "DEBUG"

mail:
  sending: OFF
  message_subject: "Load-balancer notification"
  from: "user@domain.com"
  to: "admin@domain.com"
  login: "user"
  password: "MAIL_PASSWORD"
  server:
    address: "mx.domain.com"
    port: 25
  ssl_tls: OFF

Gigabyte: 1073741824
Terabyte: 1099511627776
